pkg/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
	<description>DocuSign Log</description>
	<label>DocuSign Log</label>
	<nameField>
		<displayFormat>DSL-{0000000}</displayFormat>
		<label>DocuSign Log</label>
		<type>AutoNumber</type>
	</nameField>
	<pluralLabel>DocuSign Logs</pluralLabel>
	<sharingModel>Read</sharingModel>
</CustomObject>

pkg/main/default/objects/Log__c/fields/Class__c.field-meta.xml
<CustomField>
	<externalId>true</externalId>
	<fullName>Class__c</fullName>
	<label>Class</label>
	<length>100</length>
	<type>Text</type>
</CustomField>

pkg/main/default/objects/Log__c/fields/EntityId__c.field-meta.xml
<CustomField>
	<externalId>true</externalId>
	<fullName>EntityId__c</fullName>
	<label>DocuSign entity ID</label>
	<length>36</length>
	<type>Text</type>
</CustomField>

pkg/main/default/objects/Log__c/fields/Message__c.field-meta.xml
<CustomField>
	<fullName>Message__c</fullName>
	<label>Message</label>
	<length>131072</length>
	<type>LongTextArea</type>
</CustomField>

pkg/main/default/objects/Log__c/fields/Method__c.field-meta.xml
<CustomField>
	<fullName>Method__c</fullName>
	<label>Method</label>
	<length>100</length>
	<type>Text</type>
</CustomField>

pkg/main/default/objects/Log__c/fields/Severity__c.field-meta.xml
<CustomField>
	<fullName>Severity__c</fullName>
	<label>Severity</label>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetDefinition>
			<value>
				<fullName>DEBUG</fullName>
			</value>
			<value>
				<fullName>INFO</fullName>
			</value>
			<value>
				<fullName>WARN</fullName>
			</value>
			<value>
				<fullName>ERROR</fullName>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

pkg/main/default/objects/Log__c/fields/SourceId__c.field-meta.xml
<CustomField>
	<externalId>true</externalId>
	<fullName>SourceId__c</fullName>
	<label>Salesforce source ID</label>
	<length>18</length>
	<type>Text</type>
</CustomField>

pkg/main/default/objects/Log__c/fields/TransactionId__c.field-meta.xml
<CustomField>
	<externalId>true</externalId>
	<fullName>TransactionId__c</fullName>
	<label>Transaction ID</label>
	<length>36</length>
	<type>Text</type>
</CustomField>

pkg/main/default/objects/ProductSettings__c/ProductSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Products</label>
</CustomObject>

pkg/main/default/objects/ProductSettings__c/fields/Features__c.field-meta.xml
<CustomField>
	<fullName>Features__c</fullName>
	<defaultValue>0</defaultValue>
	<description>Feature Flags</description>
	<inlineHelpText>Feature Flags</inlineHelpText>
	<label>Feature Flags</label>
	<precision>10</precision>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

pkg/main/default/classes/ConnectConfigurationPostInstallTest.cls
@IsTest
private class ConnectConfigurationPostInstallTest {

	@IsTest
	static void test_createConfiguration_connect_disabled() {
		System.runAs(UserMock.createDocuSignAdministrator()) {
			ProductSettings__c ps = ProductSettings__c.getInstance(Product.ESIGNATURE);
			ps.Features__c = 0;
			update ps;

			Test.startTest();
			ConnectConfigurationPostInstall.createConfiguration();
			Test.stopTest();

			List<Log__c> logs = [
				SELECT Severity__c, Message__c, TransactionId__c, EntityId__c, SourceId__c, Class__c, Method__c
				FROM Log__c
			];
			System.assertEquals(1, Collection.size(logs));
			Log__c log = logs[0];
			System.assertNotEquals(null, log);
			System.assertEquals(LoggingLevel.WARN.name(), log.Severity__c);
			System.assertEquals(Label.ConnectNotEnabled, log.Message__c);
			System.assertNotEquals(null, log.TransactionId__c);
			System.assertEquals(null, log.EntityId__c);
			System.assertEquals(null, log.SourceId__c);
			System.assertEquals(String.valueOf(ConnectConfigurationPostInstall.class), log.Class__c);
			System.assertEquals('createConfiguration', log.Method__c);
		}
	}

	@IsTest
	static void test_createConfiguration_error() {
		DocuSignAPIMock.failure();
		System.runAs(UserMock.createDocuSignAdministrator()) {
			Test.startTest();
			ConnectConfigurationPostInstall.createConfiguration();
			Test.stopTest();

			List<Log__c> logs = [
				SELECT Severity__c, Message__c, TransactionId__c, EntityId__c, SourceId__c, Class__c, Method__c
				FROM Log__c
			];
			System.assertEquals(1, Collection.size(logs));
			Log__c log = logs[0];
			System.assertNotEquals(null, log);
			System.assertEquals(LoggingLevel.ERROR.name(), log.Severity__c);
			System.assertNotEquals(null, log.Message__c);
			System.assert(log.Message__c.startsWith(Label.ConnectConfigurationError));
			System.assertNotEquals(null, log.TransactionId__c);
			System.assertEquals(null, log.EntityId__c);
			System.assertEquals(null, log.SourceId__c);
			System.assertEquals(String.valueOf(ConnectConfigurationPostInstall.class), log.Class__c);
			System.assertEquals('createConfiguration', log.Method__c);
		}
	}

	@IsTest
	static void test_createConfiguration_success() {
		DocuSignAPIMock.success();
		System.runAs(UserMock.createDocuSignAdministrator()) {
			Test.startTest();
			ConnectConfigurationPostInstall.createConfiguration();
			Test.stopTest();

			System.assertEquals(0, [SELECT COUNT() FROM Log__c]);
		}
	}

	@IsTest
	static void test_shouldExecute_false() {
		ConnectConfigurationPostInstall ccpi = new ConnectConfigurationPostInstall();

		Test.startTest();
		System.assert(!ccpi.shouldExecute(
			UserInfo.getOrganizationId(),
			UserInfo.getUserId(),
			new Version(2, 4),
			false,
			false));
		System.assert(!ccpi.shouldExecute(
			UserInfo.getOrganizationId(),
			UserInfo.getUserId(),
			new Version(2, 5),
			false,
			true));
		Test.stopTest();
	}

	@IsTest
	static void test_shouldExecute_true() {
		ConnectConfigurationPostInstall ccpi = new ConnectConfigurationPostInstall();

		Test.startTest();
		System.assert(ccpi.shouldExecute(
			UserInfo.getOrganizationId(),
			UserInfo.getUserId(),
			new Version(2, 4),
			false,
			true));
		Test.stopTest();
	}

	@IsTest
	static void test_execute_skip() {
		ConnectConfigurationPostInstall ccpi = new ConnectConfigurationPostInstall();

		Test.startTest();
		PostInstallResults result = ccpi.execute(
			UserInfo.getOrganizationId(),
			UserInfo.getUserId(),
			new Version(2, 6),
			false,
			true);
		Test.stopTest();

		System.assertNotEquals(null, result);
		System.assert(result.success);
		System.assertEquals(1, Collection.size(result.getSteps()));
		System.assertEquals(Label.CreateConnectConfiguration, result.getSteps()[0].name);
		System.assertEquals(PostInstallResults.StepStatus.SKIPPED, result.getSteps()[0].status);
		System.assertEquals(Label.PostInstallCriteriaNotMet, result.getSteps()[0].context);
	}

	@IsTest
	static void test_execute_account_not_configured() {
		System.runAs(UserMock.createDocuSignAdministrator(false)) {
			ConnectConfigurationPostInstall ccpi = new ConnectConfigurationPostInstall();

			Test.startTest();
			PostInstallResults result = ccpi.execute(
				UserInfo.getOrganizationId(),
				UserInfo.getUserId(),
				new Version(2, 4),
				false,
				true);
			Test.stopTest();

			System.assertNotEquals(null, result);
			System.assert(result.success);
			System.assertEquals(1, Collection.size(result.getSteps()));
			System.assertEquals(Label.CreateConnectConfiguration, result.getSteps()[0].name);
			System.assertEquals(PostInstallResults.StepStatus.SKIPPED, result.getSteps()[0].status);
			System.assertEquals(Label.AccountNotConfigured, result.getSteps()[0].context);
		}
	}

	@IsTest
	static void test_execute_success() {
		DocuSignAPIMock.success();
		System.runAs(UserMock.createDocuSignAdministrator()) {
			ConnectConfigurationPostInstall ccpi = new ConnectConfigurationPostInstall();

			Test.startTest();
			PostInstallResults result = ccpi.execute(
				UserInfo.getOrganizationId(),
				UserInfo.getUserId(),
				new Version(2, 4),
				false,
				true);
			Test.stopTest();

			System.assertNotEquals(null, result);
			System.assert(result.success);
			System.assertEquals(1, Collection.size(result.getSteps()));
			System.assertEquals(Label.CreateConnectConfiguration, result.getSteps()[0].name);
			System.assertEquals(PostInstallResults.StepStatus.SUCCESS, result.getSteps()[0].status);
		}
	}
}