src/objects/AccountSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<fields>
		<fullName>SetupComplete__c</fullName>
		<defaultValue>false</defaultValue>
		<label>Setup Complete</label>
		<type>Checkbox</type>
	</fields>
	<fields>
		<fullName>Environment__c</fullName>
		<label>DocuSign Environment</label>
		<length>20</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>BaseUrl__c</fullName>
		<label>DocuSign Base URL</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>AccountId__c</fullName>
		<label>DocuSign Account ID</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>UseSendOnBehalfOf__c</fullName>
		<defaultValue>true</defaultValue>
		<label>Use Send on Behalf of (SOBO)</label>
		<type>Checkbox</type>
	</fields>
	<fields>
		<fullName>Username__c</fullName>
		<label>DocuSign Username</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>Password__c</fullName>
		<label>DocuSign API Password</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>EntityResolvers__c</fullName>
		<label>Entity Resolvers</label>
		<length>255</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>DocumentResolvers__c</fullName>
		<label>Document Resolvers</label>
		<length>255</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>RecipientResolvers__c</fullName>
		<label>Entity Resolvers</label>
		<length>255</length>
		<type>Text</type>
	</fields>
	<label>Account Settings</label>
</CustomObject>

src/objects/ChatterSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<label>Chatter Settings</label>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
	<description>DocuSign Envelope Document</description>
	<fields>
		<fullName>Envelope__c</fullName>
		<description>Envelope</description>
		<inlineHelpText>Envelope</inlineHelpText>
		<label>DocuSign Envelope</label>
		<referenceTo>Envelope__c</referenceTo>
		<relationshipLabel>DocuSign Envelope Documents</relationshipLabel>
		<relationshipName>Documents</relationshipName>
		<type>MasterDetail</type>
	</fields>
	<fields>
		<fullName>Extension__c</fullName>
		<label>Extension</label>
		<length>20</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>Sequence__c</fullName>
		<defaultValue>1</defaultValue>
		<description>Sequence</description>
		<label>Sequence</label>
		<precision>6</precision>
		<scale>0</scale>
		<type>Number</type>
	</fields>
	<fields>
		<fullName>SourceId__c</fullName>
		<label>Source ID</label>
		<length>40</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>Type__c</fullName>
		<description>Document Type</description>
		<inlineHelpText>Document Type</inlineHelpText>
		<label>Document Type</label>
		<type>Picklist</type>
		<valueSet>
			<valueSetDefinition>
				<value>
					<fullName>File</fullName>
				</value>
				<value>
					<fullName>Template</fullName>
				</value>
				<value>
					<fullName>Document</fullName>
				</value>
				<value>
					<fullName>Other</fullName>
				</value>
			</valueSetDefinition>
		</valueSet>
	</fields>
	<fields>
		<fullName>Size__c</fullName>
		<description>Document Size</description>
		<inlineHelpText>Document Size</inlineHelpText>
		<label>Document Size</label>
		<precision>12</precision>
		<scale>0</scale>
		<type>Number</type>
	</fields>
	<label>DocuSign Envelope Document</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>DocuSign Envelope Documents</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Envelope__c.object
<CustomObject>
	<description>DocuSign Envelope</description>
	<fields>
		<fullName>DocuSignId__c</fullName>
		<description>DocuSign ID</description>
		<inlineHelpText>DocuSign ID</inlineHelpText>
		<label>DocuSign ID</label>
		<length>40</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>EmailSubject__c</fullName>
		<defaultValue>&quot;Documents for your DocuSign Signature&quot;</defaultValue>
		<description>Email Subject</description>
		<inlineHelpText>Change this default Email Subject text and it will appear as the Subject Line in the
			notification to Sign for your DocuSign Recipients.
		</inlineHelpText>
		<label>Email subject</label>
		<length>255</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>EmailMessage__c</fullName>
		<description>Email Message</description>
		<inlineHelpText>Edit this Email Message Text (up to 2,000 characters) and it will appear in the notification to
			sign for your DocuSign Recipient.
		</inlineHelpText>
		<label>Email message</label>
		<length>2000</length>
		<type>LongTextArea</type>
	</fields>
	<fields>
		<fullName>SourceId__c</fullName>
		<description>Salesforce source ID</description>
		<inlineHelpText>Salesforce source ID</inlineHelpText>
		<label>Salesforce source ID</label>
		<length>18</length>
		<type>Text</type>
	</fields>
	<label>DocuSign Envelope</label>
	<nameField>
		<displayFormat>DSE-{0000000}</displayFormat>
		<label>DocuSign Envelope</label>
		<type>AutoNumber</type>
	</nameField>
	<pluralLabel>DocuSign Envelopes</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EnvelopeLocalization__c.object
<CustomObject>
	<fields>
		<fullName>Language__c</fullName>
		<description>Language Code</description>
		<label>Language Code</label>
		<length>30</length>
		<type>Text</type>
		<unique>true</unique>
	</fields>
	<fields>
		<fullName>EmailSubject__c</fullName>
		<description>Email Subject</description>
		<label>Email Subject</label>
		<length>255</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>EmailMessage__c</fullName>
		<description>Email Message</description>
		<label>Email Message</label>
		<length>2000</length>
		<type>LongTextArea</type>
	</fields>
	<nameField>
		<type>Text</type>
		<label>Language</label>
	</nameField>
	<label>DocuSign Localization</label>
	<pluralLabel>DocuSign Localizations</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EnvelopeSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<label>Envelope Settings</label>
</CustomObject>

src/objects/Recipient__c.object
<CustomObject>
	<description>DocuSign Envelope Recipient</description>
	<fields>
		<fullName>Envelope__c</fullName>
		<description>DocuSign Envelope</description>
		<inlineHelpText>DocuSign Envelope</inlineHelpText>
		<label>DocuSign Envelope</label>
		<referenceTo>Envelope__c</referenceTo>
		<relationshipLabel>DocuSign Envelope Recipients</relationshipLabel>
		<relationshipName>Recipients</relationshipName>
		<type>MasterDetail</type>
	</fields>
	<fields>
		<fullName>Type__c</fullName>
		<description>Type</description>
		<inlineHelpText>Type</inlineHelpText>
		<label>Type</label>
		<type>Picklist</type>
		<valueSet>
			<valueSetDefinition>
				<value>
					<fullName>Signer</fullName>
					<default>true</default>
					<label>Needs to Sign</label>
				</value>
				<value>
					<fullName>InPersonSigner</fullName>
					<label>In Person Signer</label>
				</value>
				<value>
					<fullName>CarbonCopy</fullName>
					<label>Receives a Copy</label>
				</value>
				<value>
					<fullName>CertifiedDelivery</fullName>
					<label>Needs to View</label>
				</value>
				<value>
					<fullName>Agent</fullName>
					<label>Specify Recipients</label>
				</value>
				<value>
					<fullName>Editor</fullName>
					<label>Allow to Edit</label>
				</value>
				<value>
					<fullName>Intermediary</fullName>
					<label>Update Recipients</label>
				</value>
			</valueSetDefinition>
		</valueSet>
	</fields>
	<fields>
		<fullName>EmailMessage__c</fullName>
		<label>Email Message</label>
		<length>10000</length>
		<type>LongTextArea</type>
	</fields>
	<fields>
		<fullName>EmailSubject__c</fullName>
		<label>Email Subject</label>
		<length>1000</length>
		<type>LongTextArea</type>
	</fields>
	<fields>
		<fullName>Language__c</fullName>
		<label>Language</label>
		<length>10</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>SourceId__c</fullName>
		<label>Source ID</label>
		<length>18</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>Sequence__c</fullName>
		<label>Sequence</label>
		<precision>6</precision>
		<scale>0</scale>
		<type>Number</type>
	</fields>
	<label>DocuSign Envelope Recipient</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>DocuSign Envelope Recipients</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RoleSettings__c.object
<CustomObject>
	<customSettingsType>List</customSettingsType>
	<fields>
		<fullName>Value__c</fullName>
		<label>Role Value</label>
		<precision>6</precision>
		<required>true</required>
		<scale>0</scale>
		<type>Number</type>
		<unique>true</unique>
	</fields>
	<label>Roles</label>
</CustomObject>

src/objects/User.object
<CustomObject>
	<fields>
		<fullName>Username__c</fullName>
		<description>DocuSign username</description>
		<label>DocuSign username</label>
		<length>100</length>
		<type>Text</type>
	</fields>
</CustomObject>

src/objects/UserSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<fields>
		<fullName>Username__c</fullName>
		<label>DocuSign Username</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>Password__c</fullName>
		<label>DocuSign API Password</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<label>User Settings</label>
</CustomObject>

src/classes/TestUtils.cls
@IsTest
public class TestUtils {

	public static final String BASE_URL = 'https://unit.test.docusign.net/';
	public static final UUID ID1 = UUID.fromString('11111111-1111-1111-1111-111111111111');
	public static final UUID ID2 = UUID.fromString('22222222-2222-2222-2222-222222222222');
	public static final UUID ID3 = UUID.fromString('33333333-3333-3333-3333-333333333333');
	public static final UUID ID4 = UUID.fromString('44444444-4444-4444-4444-444444444444');
	public static final UUID ID5 = UUID.fromString('55555555-5555-5555-5555-555555555555');

	private static User administrator = null;

	private static User getAdministrator() {
		if (administrator == null) {
			administrator = createUser('System Administrator');
		}
		return administrator;
	}

	public static User createDocuSignAdministrator() {
		return createDocuSignAdministrator(UUID.randomUUID().toString(), null);
	}

	public static User createDocuSignAdministrator(final String dsUsername) {
		return createDocuSignAdministrator(dsUsername, null);
	}

	public static User createDocuSignAdministrator(final String dsUsername, final String dsPassword) {
		User u = createUser(UserInfo.getProfileId(), UUID.randomUUID().toString() + '@unit.test', dsUsername);
		if (String.isNotBlank(dsUsername)) {
			UserSettings__c us = UserSettings__c.getInstance(u.Id);
			us.Username__c = dsUsername;
			us.Password__c = dsPassword;
			upsert us;
		}
		System.runAs(getAdministrator()) {
			Permissions.assignDocuSignAdministratorPermissionSet(new Set<Id> { u.Id });
		}
		return u;
	}

	public static User createDocuSignUser() {
		return createDocusignUser(UUID.randomUUID().toString(), null);
	}

	public static User createDocuSignUser(final String dsUsername) {
		return createDocuSignUser(dsUsername, null);
	}

	public static User createDocuSignUser(final String dsUsername, final String dsPassword) {
		User u = createUser(UserInfo.getProfileId(), UUID.randomUUID().toString() + '@unit.test', dsUsername);
		if (String.isNotBlank(dsUsername)) {
			UserSettings__c us = UserSettings__c.getInstance(u.Id);
			us.Username__c = dsUsername;
			us.Password__c = dsPassword;
			upsert us;
		}
		System.runAs(getAdministrator()) {
			Permissions.assignDocuSignUserPermissionSet(new Set<Id> { u.Id });
		}
		return u;
	}

	public static User createAdministrator() {
		return createUser('System Administrator');
	}

	public static User createRestrictedUser() {
		return createUser('Chatter Free User');
	}

	public static User createUser() {
		return createUser('Standard User');
	}

	public static User createUser(final String profileName) {
		Profile p = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1];
		return createUser(p.Id, UUID.randomUUID().toString() + '@unit.test', null);
	}

	public static User createUser(final Id profileId, final String email, final String dsUsername) {
		String ts = String.valueOf(Datetime.now().getTime());
		User u = new User(
			Email = email,
			Phone = '5555555555',
			FirstName = 'UNIT',
			LastName = 'TEST',
			Username = email,
			Alias = 'test',
			TimeZoneSidKey = 'America/Los_Angeles',
			LocaleSidKey = 'en_US',
			EmailEncodingKey = 'ISO-8859-1',
			ProfileId = profileId,
			LanguageLocaleKey = 'en_US',
			Username__c = dsUsername);
		insert u;
		return u;
	}

	public static Envelope__c createEnvelope() {
		return createEnvelope(null);
	}

	public static Envelope__c createEnvelope(final Id sourceId) {
		Envelope__c e = new Envelope__c(
			SourceId__c = sourceId,
			DocuSignId__c = UUID.randomUUID().toString(),
			EmailSubject__c = 'Subject',
			EmailMessage__c = 'Message');
		insert e;
		return e;
	}

	public static ContentVersion createContentVersion() {
		UUID id = UUID.randomUUID();
		ContentVersion cv = new ContentVersion(
			Title = id.toString(),
			PathOnClient = id.toString() + '.pdf',
			VersionData = Blob.valueOf(UUID.randomUUID().toString()));
		insert cv;
		return [SELECT ContentDocumentId, Title, PathOnClient, FileExtension, VersionData, ContentSize FROM ContentVersion WHERE Id = :cv.Id LIMIT 1];
	}

	public static Document__c createEnvelopeDocument(final Id envelopeId) {
		return createEnvelopeDocument(envelopeId, createContentVersion(), 1);
	}

	public static Document__c createEnvelopeDocument(final Id envelopeId, final Integer sequence) {
		return createEnvelopeDocument(envelopeId, createContentVersion(), sequence);
	}

	public static Document__c createEnvelopeDocument(final Id envelopeId, final String type, final Id id, final String name, final Integer sequence) {
		Document__c ed = new Document__c(
			Envelope__c = envelopeId,
			Name = name,
			SourceId__c = id,
			Sequence__c = sequence,
			Size__c = 1234,
			Extension__c = 'pdf',
			Type__c = type);
		insert ed;
		return ed;
	}

	public static Document__c createEnvelopeDocument(final Id envelopeId, final ContentVersion file, final Integer sequence) {
		return createEnvelopeDocument(envelopeId, file, Document.TYPE_FILE, sequence);
	}

	public static Document__c createEnvelopeDocument(final Id envelopeId, final ContentVersion file, final String type, final Integer sequence) {
		Document__c ed = new Document__c(
			Envelope__c = envelopeId,
			Name = file.Title,
			SourceId__c = file.Id,
			Sequence__c = sequence,
			Size__c = file.ContentSize,
			Extension__c = file.FileExtension,
			Type__c = type);
		insert ed;
		return ed;
	}

	public static Document__c createEnvelopeDocument(final Id envelopeId, final Schema.Document doc, final Integer sequence) {
		Document__c ed = new Document__c(
			Envelope__c = envelopeId,
			Name = doc.Name,
			SourceId__c = doc.Id,
			Sequence__c = sequence,
			Size__c = 1234,
			Extension__c = 'pdf',
			Type__c = Document.TYPE_DOCUMENT);
		insert ed;
		return ed;
	}

	public static Recipient__c createEnvelopeRecipient(final Id envelopeId) {
		return createEnvelopeRecipient(envelopeId, 1);
	}

	public static Recipient__c createEnvelopeRecipient(final Id envelopeId, final Integer sequence) {
		Recipient__c r = new Recipient__c(
			Envelope__c = envelopeId,
			Sequence__c = sequence);
		insert r;
		return r;
	}

	public static Schema.Account createAccount() {
		Schema.Account a = new Schema.Account(Name = 'UNIT TEST');
		insert a;
		return a;
	}

	public static Opportunity createOpportunity() {
		return createOpportunity(createAccount().Id);
	}

	public static Opportunity createOpportunity(final Id accountId) {
		Opportunity o = new Opportunity(
			AccountId = accountId,
			Name = 'UNIT TEST',
			CloseDate = Date.today(),
			StageName = 'Negotiation/Review');
		insert o;
		return o;
	}

	public static Case createCase() {
		return createCase(createAccount().Id);
	}

	public static Case createCase(final Id accountId) {
		Case c = new Case(AccountId = accountId);
		insert c;
		c = [SELECT Id, CaseNumber, Account.Id, Account.Name FROM Case WHERE Id = :c.Id];
		return c;
	}

	public static Contact createContact() {
		return createContact(createAccount().Id);
	}

	public static Contact createContact(final Id accountId) {
		Contact c = new Contact(
			AccountId = accountId,
			FirstName = 'UNIT',
			LastName = 'TEST',
			Email = UUID.randomUUID().toString() + '@unit.test',
			Phone = '5555555555');
		insert c;
		return c;
	}

	public static Lead createLead() {
		final Lead l = new Lead(
			FirstName = 'UNIT',
			LastName = 'TEST',
			Company = 'Acme Corp.',
			Email = UUID.randomUUID().toString() + '@unit.test',
			Phone = '5555555555');
		insert l;
		return l;
	}

	public static UUID createAccountConfiguration() {
		final UUID accountId = UUID.randomUUID();
		return createAccountConfiguration(accountId, accountId.toString() + '@unit.test');
	}

	public static UUID createAccountConfiguration(final UUID accountId, final String username) {
		AccountSettings__c accountSettings = AccountSettings__c.getOrgDefaults();
		accountSettings.Environment__c = 'other';
		accountSettings.BaseUrl__c = BASE_URL;
		accountSettings.AccountId__c = String.valueOf(accountId);
		accountSettings.Username__c = username;
		accountSettings.Password__c = UUID.randomUUID().toShortString();
		accountSettings.UseSendOnBehalfOf__c = true;
		accountSettings.SetupComplete__c = true;
		accountSettings.EntityResolvers__c = Application.classNamespacePrefix + 'DefaultEntityResolver';
		accountSettings.DocumentResolvers__c = Application.classNamespacePrefix + 'DefaultDocumentResolver';
		accountSettings.RecipientResolvers__c = Application.classNamespacePrefix + 'DefaultRecipientResolver';
		insert accountSettings;

		insert EnvelopeSettings__c.getOrgDefaults();

		insert ChatterSettings__c.getOrgDefaults();

		insert new List<RoleSettings__c> {
			new RoleSettings__c(Name = 'Signer 1', Value__c = 1),
			new RoleSettings__c(Name = 'Signer 2', Value__c = 2),
			new RoleSettings__c(Name = 'Signer 3', Value__c = 3),
			new RoleSettings__c(Name = 'Signer 4', Value__c = 4)
		};

		insert new EnvelopeLocalization__c(
			Name = 'English',
			Language__c = 'en',
			EmailSubject__c = 'Please sign this document',
			EmailMessage__c = 'This email contains a document');
		return accountId;
	}

	public static Schema.Document createDocument() {
		return createDocument(UserInfo.getUserId());
	}

	public static Schema.Document createDocument(final Id folderId) {
		Schema.Document d = new Schema.Document(
			Name = UUID.randomUUID().toString() + '.pdf',
			Body = Blob.valueOf(UUID.randomUUID().toString()),
			FolderId = folderId);
		insert d;
		return [SELECT Name, Type, Body, BodyLength, FolderId FROM Document WHERE Id = :d.Id LIMIT 1];
	}

	public static ContentWorkspace createContentWorkspace() {
		ContentWorkspace cw = new ContentWorkspace(Name = UUID.randomUUID().toString());
		insert cw;
		return cw;
	}

	public static ContentWorkspace getFirstAvailableContentWorkspace() {
		List<ContentWorkspace> cws = [SELECT Id, Name FROM ContentWorkspace ORDER BY Name LIMIT 1];
		if (Collection.isNotEmpty(cws)) {
			return cws[0];
		}
		return null;
	}

	public static ContentWorkspaceDoc createContentWorkspaceDoc(final Id contentWorkspaceId, final Id contentDocumentId) {
		ContentWorkspaceDoc cwd = new ContentWorkspaceDoc(
			ContentWorkspaceId = contentWorkspaceId,
			ContentDocumentId = contentDocumentId);
		insert cwd;
		return cwd;
	}

	public static ContentDocumentLink createContentDocumentLink(final Id linkedEntityId) {
		return createContentDocumentLink(linkedEntityId, createContentVersion());
	}

	public static ContentDocumentLink createContentDocumentLink(final Id linkedEntityId, final ContentVersion contentVersion) {
		ContentDocumentLink cdl = new ContentDocumentLink(
			ContentDocumentId = contentVersion.ContentDocumentId,
			LinkedEntityId = linkedEntityId,
			ShareType = 'I');
		insert cdl;
		return cdl;
	}
}