src/objects/AccountSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<fields>
		<fullName>Environment__c</fullName>
		<label>DocuSign Environment</label>
		<length>20</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>AccountId__c</fullName>
		<label>DocuSign Account ID</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>Username__c</fullName>
		<label>DocuSign Username</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<label>Account Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
	<fields>
		<fullName>Username__c</fullName>
		<description>DocuSign username</description>
		<label>DocuSign username</label>
		<length>100</length>
		<type>Text</type>
	</fields>
</CustomObject>

pkg/main/default/classes/UserEventsControllerTest.cls
@IsTest
private class UserEventsControllerTest {

	@IsTest
	static void test_getUserProperties_failure() {
		System.runAs(UserMock.createRestrictedUser()) {
			Test.startTest();
			try {
				UserEventsController.getUserProperties();
				throw new AssertException('Expected failure');
			} catch (AuraHandledException ex) {
				System.assertNotEquals(null, ex);
				System.assert(String.isNotBlank(ex.getMessage()));
			}
			Test.stopTest();
		}
	}

	@IsTest
	static void test_getUserProperties_success() {
		System.runAs(UserMock.createDocuSignUser()) {
			Test.startTest();
			UserEventsController.UserProperties result1 = UserEventsController.getUserProperties();
			UserEventsController.UserProperties result2 = UserEventsController.getUserProperties();
			Test.stopTest();

			System.assertNotEquals(null, result1);
			System.assert(result1 === result2);
			System.assertEquals(Application.name, result1.application);
			System.assertEquals(String.valueOf(Application.version), result1.version);
			AccountSettings__c s = AccountSettings__c.getOrgDefaults();
			System.assertEquals(s.Environment__c, result1.environment);
			System.assertEquals(StringUtils.hash(s.AccountId__c), result1.accountIdHash);
			String username = [SELECT Username__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1].Username__c;
			System.assertEquals(StringUtils.hash(username), result1.userIdHash);
		}
	}
}