src/objects/AccountSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<fields>
		<fullName>Environment__c</fullName>
		<label>DocuSign Environment</label>
		<length>20</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>AccountId__c</fullName>
		<label>DocuSign Account ID</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>Features__c</fullName>
		<defaultValue>0</defaultValue>
		<description>Account Feature Flags</description>
		<inlineHelpText>Account Feature Flags</inlineHelpText>
		<label>Account Feature Flags</label>
		<precision>10</precision>
		<scale>0</scale>
		<type>Number</type>
	</fields>
	<label>Account Settings</label>
</CustomObject>

pkg/main/default/objects/AccountSettings__c/fields/CreateConnectConfiguration__c.field-meta.xml
<CustomField>
	<fullName>CreateConnectConfiguration__c</fullName>
	<defaultValue>false</defaultValue>
	<label>Create Connect Configuration</label>
	<type>Checkbox</type>
</CustomField>

pkg/main/default/objects/AccountSettings__c/fields/ESignatureBaseUrl__c.field-meta.xml
<CustomField>
    <fullName>ESignatureBaseUrl__c</fullName>
    <label>DocuSign eSignature API Base URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pkg/main/default/objects/ProductSettings__c/ProductSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Products</label>
</CustomObject>

pkg/main/default/objects/ProductSettings__c/fields/Features__c.field-meta.xml
<CustomField>
	<fullName>Features__c</fullName>
	<defaultValue>0</defaultValue>
	<description>Feature Flags</description>
	<inlineHelpText>Feature Flags</inlineHelpText>
	<label>Feature Flags</label>
	<precision>10</precision>
	<scale>0</scale>
	<type>Number</type>
</CustomField>

pkg/main/default/classes/ConnectConfigurationPostInstall.cls
/**
 * No sharing declaration here as it's run as part of post-install. "with sharing" or "inherited sharing" causes
 * package installation to fail with "Insufficient Privileges" error. Some code is duplicated to avoid instantiating
 * "with sharing" classes.
 */
public class ConnectConfigurationPostInstall implements PostInstallScript {

	private static final Integer FLAG_CONNECT = 32;

	@TestVisible
	private static Boolean isConnectEnabled() {
		AccountSettings__c accountSettings = AccountSettings__c.getOrgDefaults();
		ProductSettings__c eSignSettings = ProductSettings__c.getInstance(Product.ESIGNATURE);
		return accountSettings != null
			&& eSignSettings != null
			&& String.isNotBlank(accountSettings.AccountId__c)
			&& String.isNotBlank(accountSettings.Environment__c)
			&& String.isNotBlank(accountSettings.ESignatureBaseUrl__c)
			&& eSignSettings.Features__c != null
			&& (Integer.valueOf(eSignSettings.Features__c) & FLAG_CONNECT) == FLAG_CONNECT;
	}

	public Boolean shouldExecute(
		final Id organizationId,
		final Id installerId,
		final Version previousVersion,
		final Boolean isPush,
		final Boolean isUpgrade) {

		// Only execute if upgrading from < v2.5 and Connect is enabled for the account.
		return isUpgrade
			&& previousVersion != null
			&& previousVersion.major() <= 2
			&& previousVersion.minor() < 5
			&& isConnectEnabled();
	}

	public PostInstallResults execute(
		final Id organizationId,
		final Id installerId,
		final Version previousVersion,
		final Boolean isPush,
		final Boolean isUpgrade) {

		if (!this.shouldExecute(organizationId, installerId, previousVersion, isPush, isUpgrade)) {
			return new PostInstallResults().skipStep(Label.CreateConnectConfiguration, Label.PostInstallCriteriaNotMet);
		}

		AccountSettings__c accountSettings = AccountSettings__c.getOrgDefaults();
		accountSettings.CreateConnectConfiguration__c = true;
		update accountSettings;

		PostInstallResults result = new PostInstallResults();
		result.endStepSuccess(Label.CreateConnectConfiguration);

		return result;
	}
}