src/objects/AccountSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<label>Account Settings</label>
</CustomObject>

src/objects/BulkList__c.object
<CustomObject>
	<description>DocuSign Bulk Send List</description>
	<label>DocuSign Bulk Send List</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>DocuSign Bulk Send Lists</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BulkStatus__c.object
<CustomObject>
	<description>DocuSign Bulk Send Status</description>
	<label>DocuSign Bulk Send Status</label>
	<nameField>
		<displayFormat>DSX-{0000000}</displayFormat>
		<label>Envelope#</label>
		<type>AutoNumber</type>
	</nameField>
	<pluralLabel>DocuSign Bulk Send Status</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ChatterSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<label>Chatter Settings</label>
</CustomObject>

src/objects/CustomParameterMap__c.object
<CustomObject>
	<fields>
		<fullName>EnvelopeConfiguration__c</fullName>
		<description>DocuSign Envelope Configuration</description>
		<inlineHelpText>DocuSign Envelope Configuration</inlineHelpText>
		<label>DocuSign Envelope Configuration</label>
		<referenceTo>EnvelopeConfiguration__c</referenceTo>
		<relationshipName>CustomParameterMap</relationshipName>
		<relationshipOrder>0</relationshipOrder>
		<type>MasterDetail</type>
	</fields>
	<label>DocuSign Custom Parameter Map</label>
	<nameField>
		<displayFormat>CPM{000000}</displayFormat>
		<label>Name</label>
		<type>AutoNumber</type>
	</nameField>
	<pluralLabel>DocuSign Custom Parameter Maps</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CustomRecipient__c.object
<CustomObject>
	<fields>
		<fullName>EnvelopeConfiguration__c</fullName>
		<label>DocuSign Envelope Configuration</label>
		<referenceTo>EnvelopeConfiguration__c</referenceTo>
		<relationshipLabel>Custom Recipients</relationshipLabel>
		<relationshipName>CustomRecipient</relationshipName>
		<relationshipOrder>0</relationshipOrder>
		<type>MasterDetail</type>
	</fields>
	<label>DocuSign Custom Recipient</label>
	<nameField>
		<displayFormat>CBR-{000000}</displayFormat>
		<label>Name</label>
		<type>AutoNumber</type>
	</nameField>
	<pluralLabel>Custom Recipients</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Document__c.object
<CustomObject>
	<description>DocuSign Envelope Document</description>
	<fields>
		<fullName>Envelope__c</fullName>
		<description>Envelope</description>
		<inlineHelpText>Envelope</inlineHelpText>
		<label>DocuSign Envelope</label>
		<referenceTo>Envelope__c</referenceTo>
		<relationshipLabel>DocuSign Envelope Documents</relationshipLabel>
		<relationshipName>Documents</relationshipName>
		<type>MasterDetail</type>
	</fields>
	<label>DocuSign Envelope Document</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>DocuSign Envelope Documents</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Envelope__c.object
<CustomObject>
	<description>DocuSign Envelope</description>
	<fields>
		<fullName>EnvelopeConfiguration__c</fullName>
		<deleteConstraint>SetNull</deleteConstraint>
		<label>Envelope Configuration</label>
		<inlineHelpText>The configuration used to generate this envelope.</inlineHelpText>
		<referenceTo>EnvelopeConfiguration__c</referenceTo>
		<relationshipLabel>Envelope Configuration</relationshipLabel>
		<relationshipName>EnvelopeConfiguration</relationshipName>
		<type>Lookup</type>
	</fields>
	<label>DocuSign Envelope</label>
	<nameField>
		<displayFormat>DSE-{0000000}</displayFormat>
		<label>DocuSign Envelope</label>
		<type>AutoNumber</type>
	</nameField>
	<pluralLabel>DocuSign Envelopes</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EnvelopeConfiguration__c.object
<CustomObject>
	<label>DocuSign Envelope Configuration</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>DocuSign Envelope Configurations</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EnvelopeLocalization__c.object
<CustomObject>
	<nameField>
		<type>Text</type>
		<label>Language</label>
	</nameField>
	<label>DocuSign Localization</label>
	<pluralLabel>DocuSign Localizations</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EnvelopeSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<label>Envelope Settings</label>
</CustomObject>

pkg/main/default/objects/GenTemplate__c/GenTemplate__c.object-meta.xml
<CustomObject>
	<label>DocuSign Gen Template</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>DocuSign Gen Templates</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Localization__mdt.object
<CustomObject>
	<label>DocuSign Localization Metadata</label>
	<pluralLabel>DocuSign Localization Metadata</pluralLabel>
</CustomObject>

src/objects/Organization__mdt.object
<CustomObject>
	<label>DocuSign Organization Metadata</label>
	<pluralLabel>DocuSign Organization Metadata</pluralLabel>
</CustomObject>

src/objects/Recipient__c.object
<CustomObject>
	<description>DocuSign Envelope Recipient</description>
	<fields>
		<fullName>Envelope__c</fullName>
		<description>DocuSign Envelope</description>
		<inlineHelpText>DocuSign Envelope</inlineHelpText>
		<label>DocuSign Envelope</label>
		<referenceTo>Envelope__c</referenceTo>
		<relationshipLabel>DocuSign Envelope Recipients</relationshipLabel>
		<relationshipName>Recipients</relationshipName>
		<type>MasterDetail</type>
	</fields>
	<label>DocuSign Envelope Recipient</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>DocuSign Envelope Recipients</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RecipientStatus__c.object
<CustomObject>
	<description>DocuSign Recipient Status</description>
	<fields>
		<fullName>Status__c</fullName>
		<label>Status</label>
		<length>56</length>
		<type>Text</type>
	</fields>
	<label>DocuSign Recipient Status</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>DocuSign Recipient Statuses</pluralLabel>
	<sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/UserSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<label>User Settings</label>
</CustomObject>

pkg/main/default/classes/Application.cls
/**
 * Source of truth for application metadata.
 */
public with sharing class Application {

	private static final String PACKAGE_NAMESPACE = 'dfsle';
	private static final String ORG_NAMESPACE_PREFIX;
	private static final String ORG_CLASS_NAMESPACE_PREFIX;
	private static final String NAMESPACE_PREFIX = 'dfsle__';
	private static final String CLASS_NAMESPACE_PREFIX = 'dfsle.';
	private static final Boolean IS_MANAGED_PACKAGE;
	private static final Version PACKAGE_VERSION;
	private static final String APPLICATION_NAME;
	private static final String USER_AGENT;
	private static final Set<String> APPLICATION_OBJECTS = new Set<String> {
		'envelopeconfiguration__c', 'customparametermap__c', 'customrecipient__c',
		'envelope__c', 'document__c', 'recipient__c',
		'status__c', 'recipientstatus__c', 'envelopelocalization__c',
		'accountsettings__c', 'usersettings__c', 'chattersettings__c', 'envelopesettings__c',
		'organization__mdt', 'localization__mdt', 'bulklist__c', 'bulkstatus__c',
		'gentemplate__c'
	};

	static {
		// HACK: Get managed package version: https://salesforce.stackexchange.com/questions/11049/cant-catch-system-procedureexception-thrown-by-system-requestversion
		Boolean result = null;
		try {
			result = UserInfo.isCurrentUserLicensed(PACKAGE_NAMESPACE);
			//UserInfo.isCurrentUserLicensed method has been deprecated post API version 45.0
			//Until we find a workaround for this method please do not update the API version of this Apex class.
		} catch (TypeException ex) {
			// Not managed
		}
		IS_MANAGED_PACKAGE = result != null;
		ORG_NAMESPACE_PREFIX = String.isNotBlank(Salesforce.namespace) ? Salesforce.namespace + '__' : '';
		ORG_CLASS_NAMESPACE_PREFIX = String.isNotBlank(Salesforce.namespace) ? Salesforce.namespace + '.' : '';

		// Don't call System.requestVersion outside managed package. It will throw an un-catchable ProcedureException.
		// Don't use versions < 1. They make SFDC unhappy.
		PACKAGE_VERSION = IS_MANAGED_PACKAGE ? System.requestVersion() : new Version(1, 0, 0);
		APPLICATION_NAME = 'DFS-LE ' + PACKAGE_VERSION;
		USER_AGENT = String.format('DFS-LE/{0} ({1}) SFDC-Callout/{2}', new List<String> {
			String.valueOf(PACKAGE_VERSION), UserInfo.getOrganizationId(), String.valueOf(Salesforce.API_VERSION)
		});
	}

	public static Boolean isManaged {
		get {
			return IS_MANAGED_PACKAGE;
		}
	}

	public static Version version {
		get {
			return PACKAGE_VERSION;
		}
	}

	public static String name {
		get {
			return APPLICATION_NAME;
		}
	}

	public static String packageNamespace {
		get {
			return PACKAGE_NAMESPACE;
		}
	}

	public static String namespacePrefix {
		get {
			return IS_MANAGED_PACKAGE ? NAMESPACE_PREFIX : ORG_NAMESPACE_PREFIX;
		}
	}

	public static String classNamespacePrefix {
		get {
			return IS_MANAGED_PACKAGE ? CLASS_NAMESPACE_PREFIX : ORG_CLASS_NAMESPACE_PREFIX;
		}
	}

	public static String namespace {
		get {
			return IS_MANAGED_PACKAGE ? PACKAGE_NAMESPACE : (String.isNotBlank(Salesforce.namespace) ? Salesforce.namespace : 'c');
		}
	}

	public static String userAgent {
		get {
			return USER_AGENT;
		}
	}

	public static String resolveType(final String sObjectType) {
		if (String.isBlank(sObjectType)) return null;

		String result = sObjectType.trim();
		if (APPLICATION_OBJECTS.contains(result.toLowerCase())) {
			return Application.namespacePrefix + result;
		}
		return result;
	}
}