src/objects/AccountSettings__c.object
<CustomObject>
	<customSettingsType>Hierarchy</customSettingsType>
	<label>Account Settings</label>
</CustomObject>

pkg/main/default/objects/AccountSettings__c/fields/EncryptionKey__c.field-meta.xml
<CustomField>
	<fullName>EncryptionKey__c</fullName>
	<label>AES256 encryption key</label>
	<length>255</length>
	<type>Text</type>
</CustomField>

pkg/main/default/objects/AccountSettings__c/fields/IsESignatureEnabled__c.field-meta.xml
<CustomField>
	<fullName>IsESignatureEnabled__c</fullName>
	<defaultValue>true</defaultValue>
	<label>Is eSignature Enabled</label>
	<type>Checkbox</type>
</CustomField>

pkg/main/default/objects/EOS_Type__c/EOS_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>A DFS-CLM specific custom setting to store the templates for object mappings between DFS-CLM and SpringCM.</description>
    <label>EOS Type</label>
</CustomObject>

pkg/main/default/objects/EOS_Type__c/fields/FolderName__c.field-meta.xml
<CustomField>
    <fullName>FolderName__c</fullName>
    <description>A field to store the folder name generated during the object mapping process.</description>
    <inlineHelpText>A field to store the folder name generated during the object mapping process.</inlineHelpText>
    <label>Folder Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pkg/main/default/objects/EOS_Type__c/fields/FolderNameFormat__c.field-meta.xml
<CustomField>
    <fullName>FolderNameFormat__c</fullName>
    <description>A field to store the format of the folder name that maps a Salesforce object to a folder in SpringCM.</description>
    <inlineHelpText>A field to store the format of the folder name that maps a Salesforce object to a folder in SpringCM.</inlineHelpText>
    <label>Folder Name Format</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pkg/main/default/objects/EOS_Type__c/fields/Path__c.field-meta.xml
<CustomField>
	<fullName>Path__c</fullName>
	<description>A field to store the folder path in SpringCM, generated during the object mapping process within
		Salesforce.
	</description>
	<inlineHelpText>A field to store the folder path in SpringCM, generated during the object mapping process within
		Salesforce.
	</inlineHelpText>
	<label>Path</label>
	<length>255</length>
	<required>true</required>
	<type>Text</type>
</CustomField>

pkg/main/default/objects/EOS_Type__c/fields/PathFormat__c.field-meta.xml
<CustomField>
	<fullName>PathFormat__c</fullName>
	<description>A field to store the path format of the folder name that maps a Salesforce object to a folder in
		SpringCM.
	</description>
	<inlineHelpText>A field to store the path format of the folder name that maps a Salesforce object to a folder in
		SpringCM.
	</inlineHelpText>
	<label>Path Format</label>
	<length>255</length>
	<type>Text</type>
</CustomField>

pkg/main/default/objects/EOS_Type__c/fields/Variables__c.field-meta.xml
<CustomField>
    <fullName>Variables__c</fullName>
    <description>A field to store the variable folder names.</description>
    <inlineHelpText>A field to store the variable folder names.</inlineHelpText>
    <label>Variables</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pkg/main/default/classes/PostInstall2.cls
/**
* Initializes new custom settings in 2.0.
*/
public class PostInstall2 implements PostInstallScript {
    
    @TestVisible
    private static PostInstallResults initializeAccountSettings() {
        Boolean didInit = false;
        PostInstallResults result = new PostInstallResults();
        AccountSettings__c settings = AccountSettings__c.getOrgDefaults();
        
        if (settings.IsESignatureEnabled__c != true) {
            settings.IsESignatureEnabled__c = true;
            didInit = true;
        }
        
        if (String.isBlank(settings.EncryptionKey__c)) {
            settings.EncryptionKey__c = EncodingUtil.base64Encode(Crypto.generateAesKey(256));
            didInit = true;
        }
        
        if (didInit) {
            update settings;
            result.endStepSuccess(Label.InitializeAccountSettings);
        } else {
            result.skipStep(Label.InitializeAccountSettings, Label.AlreadyComplete);
        }
        return result;
    }
    
    @TestVisible
    private static PostInstallResults createDefaultCLMObjMappings(){
        PostInstallResults result = new PostInstallResults();        
        try{
            if(EOS_Type__c.getOrgDefaults().Id == null){
                insertDefaultCLMObjMappings();                               
            } else{
                result.skipStep(Label.CreateDefaultCLMObjMappings, Label.AlreadyComplete);
            }
        }catch(Exception ex){
            result.endStepFailure(Label.CreateDefaultCLMObjMappings, ex);
        }
        return result;
    }
    
    private static void insertDefaultCLMObjMappings(){
        EOS_Type__c eos_Account = new EOS_Type__c();        
        eos_Account.FolderName__c = Label.DefaultAccountFolderName;
        eos_Account.Path__c = Label.DefaultAccountObjectMappingPath;
        eos_Account.FolderNameFormat__c	= Label.DefaultFolderNameFormat;
        eos_Account.Variables__c = Label.DefaultAccountVariables;
        eos_Account.PathFormat__c = Label.DefaultAccountPathFormat;			
        eos_Account.Name = Label.Account;
        insert eos_Account;
        
        EOS_Type__c eos_Opportunity = new EOS_Type__c();
        eos_Opportunity.FolderName__c = Label.DefaultOpportunityFolderName;
        eos_Opportunity.Path__c = Label.DefaultOpportunityObjectMappingPath;
        eos_Opportunity.FolderNameFormat__c	= Label.DefaultFolderNameFormat;
        eos_Opportunity.Variables__c = Label.DefaultOpportunityVariables;
        eos_Opportunity.PathFormat__c = Label.DefaultOpportunityPathFormat;			
        eos_Opportunity.Name = Label.Opportunity;						        
        insert eos_Opportunity;           
    }
    
    public Boolean shouldExecute(Id organizationId, Id installerId, Version previousVersion, Boolean isPush,
                                 Boolean isUpgrade) {
                                     
                                     return previousVersion != null
                                         && previousVersion.major() < 2;
                                 }
    
    public PostInstallResults execute(Id organizationId, Id installerId, Version previousVersion, Boolean isPush,
                                      Boolean isUpgrade) {
                                          
                                          return new PostInstallResults().addResults(initializeAccountSettings()).addResults(createDefaultCLMObjMappings());
                                      }
}