pkg/main/default/objects/GenMigrationSettings__c/GenMigrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store settings related to Gen Package</description>
    <label>Gen Migration Settings</label>
</CustomObject>

src/objects/User.object
<CustomObject>
	<fields>
		<fullName>Username__c</fullName>
		<description>DocuSign username</description>
		<label>DocuSign username</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>CanManageAccount__c</fullName>
		<defaultValue>false</defaultValue>
		<description>Can manage DocuSign account</description>
		<label>Can manage DocuSign account</label>
		<type>Checkbox</type>
	</fields>
</CustomObject>

pkg/main/default/objects/User/fields/Provisioned__c.field-meta.xml
<CustomField>
	<fullName>Provisioned__c</fullName>
	<description>Date when the user was added to the account</description>
	<inlineHelpText>Date when the user was added to the account</inlineHelpText>
	<label>DocuSign Provisioned Date</label>
	<type>Date</type>
</CustomField>

pkg/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
	<fullName>Status__c</fullName>
	<label>Docusign Status</label>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetDefinition>
			<value>
				<fullName>Inactive</fullName>
			</value>
			<value>
				<fullName>Pending</fullName>
			</value>
			<value>
				<fullName>Active</fullName>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

pkg/main/default/classes/GenMigrationApplication.cls
public with sharing class GenMigrationApplication {

	private static final String GEN_PACKAGE_NAMESPACE = 'dsgen';
	private static final Id GEN_PACKAGE_ID = '0335A000001645T';
	private static final String GEN_NAMESPACE_PREFIX = 'dsgen__';

	public static String namespacePrefix {
		get {
			return GEN_NAMESPACE_PREFIX;
		}
	}

	private static final String USER_QUERY = 'SELECT Id, CanManageAccount__c, ' + namespacePrefix + 'Docusign_Admin__c, ' + namespacePrefix + 'Docusign_Status__c, ' + namespacePrefix + 'DocuSign_Invitation_Date__c, ' + namespacePrefix + 'Docusign_User_Id__c, ' +
		+' Provisioned__c, Status__c, Username__c FROM User WHERE Id IN (SELECT AssigneeId FROM PermissionSetAssignment WHERE PermissionSet.Name IN ( \'DocuSign_Gen_Template_Configuration\' , \'DocuSign_Gen_User\' ))';

	public static List<Sobject> getGenUsers() {
		Permissions.verifyIsQueryable(User.getSObjectType(), new List<String> {
			'Id',
			namespacePrefix + 'Docusign_Admin__c', 'email',
			namespacePrefix + 'DocuSign_Invitation_Date__c',
			namespacePrefix + 'Docusign_Status__c',
			namespacePrefix + 'Docusign_User_Id__c',
			'CanManageAccount__c',
			'Provisioned__c',
			'Status__c',
			'Username__c'
		});
		Permissions.verifyIsQueryable(PermissionSetAssignment.getSObjectType(), new List<String> { 'Id', 'permissionsetId' });
		return DATABASE.QUERY(USER_QUERY);
	}

	public static GenMigrationSettings__c getGenSettings() {
		return GenMigrationSettings__c.getOrgDefaults();
	}

	public static Boolean verifyGenPackageInstalled() {
		try {
			return UserInfo.isCurrentUserLicensedForPackage(GEN_PACKAGE_ID) && UserInfo.isCurrentUserLicensed(GEN_PACKAGE_NAMESPACE);
		} catch (Exception e) {
			return false;
		}
	}
}