pkg/main/default/objects/ContentVersion/fields/GeneratedFileFormat__c.field-meta.xml
<CustomField>
	<fullName>GeneratedFileFormat__c</fullName>
	<label>Generated File Format</label>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetDefinition>
			<value>
				<fullName>Word</fullName>
				<default>true</default>
				<label>Word</label>
			</value>
			<value>
				<fullName>PDF</fullName>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

pkg/main/default/objects/ContentVersion/fields/GeneratedFileName__c.field-meta.xml
<CustomField>
	<fullName>GeneratedFileName__c</fullName>
	<label>Generated File Name</label>
	<length>255</length>
	<type>Text</type>
</CustomField>

pkg/main/default/objects/ContentVersion/fields/GeneratedFileSuffix__c.field-meta.xml
<CustomField>
	<fullName>GeneratedFileSuffix__c</fullName>
	<label>Generated File Suffix</label>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetDefinition>
			<value>
				<fullName>name</fullName>
				<default>true</default>
				<label>name</label>
			</value>
			<value>
				<fullName>date</fullName>
			</value>
			<value>
				<fullName>name_date</fullName>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

pkg/main/default/objects/GenMigrationSettings__c/GenMigrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store settings related to Gen Package</description>
    <label>Gen Migration Settings</label>
</CustomObject>

pkg/main/default/objects/GenMigrationSettings__c/fields/GenTemplatesMigrated__c.field-meta.xml
<CustomField>
    <fullName>GenTemplatesMigrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting this value to TRUE after migrating Gen Templates</description>
    <label>AreGenTemplatesMigrated</label>
    <type>Checkbox</type>
</CustomField>

pkg/main/default/objects/GenMigrationSettings__c/fields/GenUsersMigrated__c.field-meta.xml
<CustomField>
    <fullName>GenUsersMigrated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setting this value to TRUE after migrating Gen Users</description>
    <label>AreGenUsersMigrated</label>
    <type>Checkbox</type>
</CustomField>

pkg/main/default/objects/GenMigrationSettings__c/fields/TemplateMigrationBatchId__c.field-meta.xml
<CustomField>
    <fullName>TemplateMigrationBatchId__c</fullName>
    <description>To Store Batch Id after Template Migration</description>
    <label>TemplateMigrationBatchId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

pkg/main/default/objects/GenMigrationSettings__c/fields/TemplateMigrationBatchStatus__c.field-meta.xml
<CustomField>
    <fullName>TemplateMigrationBatchStatus__c</fullName>
    <description>To Store Template Migration Batch Status</description>
    <label>TemplateMigrationBatchStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pkg/main/default/objects/GenMigrationSettings__c/fields/UserMigrationBatchId__c.field-meta.xml
<CustomField>
    <fullName>UserMigrationBatchId__c</fullName>
    <description>To Store Batch Id after User Migration</description>
    <label>UserMigrationBatchId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

pkg/main/default/objects/GenMigrationSettings__c/fields/UserMigrationBatchStatus__c.field-meta.xml
<CustomField>
    <fullName>UserMigrationBatchStatus__c</fullName>
    <description>To Store User Migration Batch Status</description>
    <label>UserMigrationBatchStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

pkg/main/default/objects/GenTemplate__c/GenTemplate__c.object-meta.xml
<CustomObject>
	<label>DocuSign Gen Template</label>
	<nameField>
		<label>Name</label>
		<type>Text</type>
	</nameField>
	<pluralLabel>DocuSign Gen Templates</pluralLabel>
	<sharingModel>ReadWrite</sharingModel>
</CustomObject>

pkg/main/default/objects/GenTemplate__c/fields/HasPreviewedDocuments__c.field-meta.xml
<CustomField>
    <fullName>HasPreviewedDocuments__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Previewed Documents</label>
    <type>Checkbox</type>
</CustomField>

pkg/main/default/objects/GenTemplate__c/fields/IsSample__c.field-meta.xml
<CustomField>
    <fullName>IsSample__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sample</label>
    <type>Checkbox</type>
</CustomField>

pkg/main/default/objects/GenTemplate__c/fields/ObjectMappings__c.field-meta.xml
<CustomField>
    <fullName>ObjectMappings__c</fullName>
    <label>Object Mappings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

pkg/main/default/objects/GenTemplate__c/fields/SignerMappings__c.field-meta.xml
<CustomField>
    <fullName>SignerMappings__c</fullName>
    <label>Signer Mappings</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

pkg/main/default/objects/GenTemplate__c/fields/StepsCompleted__c.field-meta.xml
<CustomField>
    <fullName>StepsCompleted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Steps Completed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

pkg/main/default/objects/GenTemplate__c/fields/UseAllTemplates__c.field-meta.xml
<CustomField>
    <fullName>UseAllTemplates__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Use All Templates</label>
    <type>Checkbox</type>
</CustomField>

pkg/main/default/objects/GenTemplate__c/fields/UseCurrentRecord__c.field-meta.xml
<CustomField>
    <fullName>UseCurrentRecord__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Use Current Record</label>
    <type>Checkbox</type>
</CustomField>

src/objects/User.object
<CustomObject>
	<fields>
		<fullName>Username__c</fullName>
		<description>DocuSign username</description>
		<label>DocuSign username</label>
		<length>100</length>
		<type>Text</type>
	</fields>
	<fields>
		<fullName>CanManageAccount__c</fullName>
		<defaultValue>false</defaultValue>
		<description>Can manage DocuSign account</description>
		<label>Can manage DocuSign account</label>
		<type>Checkbox</type>
	</fields>
</CustomObject>

pkg/main/default/objects/User/fields/Provisioned__c.field-meta.xml
<CustomField>
	<fullName>Provisioned__c</fullName>
	<description>Date when the user was added to the account</description>
	<inlineHelpText>Date when the user was added to the account</inlineHelpText>
	<label>DocuSign Provisioned Date</label>
	<type>Date</type>
</CustomField>

pkg/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
	<fullName>Status__c</fullName>
	<label>Docusign Status</label>
	<type>Picklist</type>
	<valueSet>
		<restricted>true</restricted>
		<valueSetDefinition>
			<value>
				<fullName>Inactive</fullName>
			</value>
			<value>
				<fullName>Pending</fullName>
			</value>
			<value>
				<fullName>Active</fullName>
			</value>
		</valueSetDefinition>
	</valueSet>
</CustomField>

pkg/main/default/classes/GenMigrationController.cls
public with sharing class GenMigrationController {

	// perm set names
	public static final String DOCUSIGN_ADMINISTRATOR = 'DocuSign_Administrator';
	private static final String DOCUSIGN_GEN_USER = 'DocuSign_Gen_User';
	private static final String DOCUSIGN_GEN_TEMPLATE_CONFIGURATION = 'DocuSign_Gen_Template_Configuration';
	public static final String DOCUSIGN_USER = 'DocuSign_User';
	public static final String DOCUSIGN_GENERATOR = 'DocuSign_Generator';
	private static final set<String> genPermissionSetNames = new set<String> { DOCUSIGN_ADMINISTRATOR, DOCUSIGN_GEN_USER, DOCUSIGN_GEN_TEMPLATE_CONFIGURATION, DOCUSIGN_USER, DOCUSIGN_GENERATOR };

	public class MigrateWrapper {
		@AuraEnabled
		public Boolean isGenPackageUser = true;

		@AuraEnabled
		public Integer onLoadUserCount { get; private set; }

		@AuraEnabled
		public Integer onLoadTemplateCount { get; private set; }

		@AuraEnabled
		public GenMigrationSettings__c getGenStatus { get; private set; }

		public MigrateWrapper(final Integer onLoadUserCount, final Integer onLoadTemplateCount, final GenMigrationSettings__c getGenStatus) {
			this.onLoadUserCount = onLoadUserCount;
			this.onLoadTemplateCount = onLoadTemplateCount;
			this.getGenStatus = getGenStatus;
		}

		public MigrateWrapper(final Boolean isGenPackageUser) {
			this.isGenPackageUser = isGenPackageUser;
		}
	}

	@AuraEnabled(Cacheable=true)
	public static MigrateWrapper isGenPackageInstalled() {
		try {
			Permissions.verifyIsDocuSignAdministrator();
			return (GenMigrationApplication.verifyGenPackageInstalled()) ? new MigrateWrapper(GenMigrationApplication.getGenUsers().size(), Database.countQuery('SELECT count() FROM ' + GenMigrationApplication.namespacePrefix + 'Template_Configuration__c'), GenMigrationApplication.getGenSettings()) : new MigrateWrapper(GenMigrationApplication.verifyGenPackageInstalled());
		} catch (Exception ex) {
			throw Controller.wrapException(ex.getMessage());
		}
	}

	public static Map<String, Id> getAllPermissionSets() {
		Permissions.verifyIsQueryable(PermissionSet.getSObjectType(), new List<String> { 'Id', 'Name' });
		Map<String, Id> permissionSetNames = new Map<String, Id>();
		for (PermissionSet permissionSet : [SELECT Id,Name FROM PermissionSet WHERE Name IN:genPermissionSetNames]) {
			permissionSetNames.put(permissionSet.Name, permissionSet.Id);
		}
		return permissionSetNames;
	}

	@AuraEnabled
	public static Id initiateUserMigration() {
		try {
			Permissions.verifyIsDocuSignAdministrator();
			Permissions.verifyIsQueryable(User.getSObjectType(), new List<String> {
				'Id',
				GenMigrationApplication.namespacePrefix + 'Docusign_Admin__c', 'email',
				GenMigrationApplication.namespacePrefix + 'DocuSign_Invitation_Date__c',
				GenMigrationApplication.namespacePrefix + 'Docusign_Status__c',
				GenMigrationApplication.namespacePrefix + 'Docusign_User_Id__c',
				'CanManageAccount__c',
				'Provisioned__c',
				'Status__c',
				'Username__c',
				'IsActive'
			});

			Permissions.verifyIsCreateable(PermissionSetAssignment.getSObjectType(), new List<String> { 'AssigneeId', 'PermissionSetId' });
			Id apexJobId = Database.executeBatch(new GenMigrationBatch('User'));
			//Passing batch Id in custom setting
			GenMigrationSettings__c genSetting = GenMigrationSettings__c.getOrgDefaults();
			genSetting.UserMigrationBatchId__c = apexJobId;
			upsert genSetting;
			return apexJobId;
		} catch (Exception ex) {
			throw Controller.wrapException(ex, 'Failed to Assign permission sets to users');
		}
	}

	@AuraEnabled
	public static Id initiateTemplateMigration() {
		try {
			Permissions.verifyIsDocuSignAdministrator();
			Permissions.verifyIsCreateable(GenTemplate__c.getSObjectType(), new List<String> {
				'Name', 'SourceObject__c', 'ObjectMappings__c', 'SignerMappings__c', 'UseAllTemplates__c',
				'UseCurrentRecord__c', 'HasPreviewedDocuments__c', 'StepsCompleted__c', 'IsSample__c'
			});
			Permissions.verifyIsCreateable(ContentDocumentLink.getSObjectType(), new List<String> {
				'ContentDocumentId', 'LinkedEntityId', 'ShareType'
			});
			Permissions.verifyIsQueryable(ContentDocumentLink.getSObjectType(), new List<String> {
				'ContentDocumentId', 'LinkedEntityId'
			});
			Permissions.verifyIsCreateable(ContentVersion.getSObjectType(), new List<String> {
				'ExternalDocumentInfo2', 'GeneratedFileFormat__c', 'GeneratedFileName__c', 'GeneratedFileSuffix__c', 'ContentDocumentId', 'Title', 'VersionData', 'PathOnClient'
			});
			Permissions.verifyIsQueryable(ContentVersion.getSObjectType(), new List<String> {
				'ContentDocumentId', 'Title', 'PathOnClient', 'VersionData',
				GenMigrationApplication.namespacePrefix + 'Generated_File_Format__c',
				GenMigrationApplication.namespacePrefix + 'Generated_File_Name__c',
				GenMigrationApplication.namespacePrefix + 'Generated_File_Suffix__c'
			});
			Schema.DescribeSobjectResult[] getGenTemplateSobject = Schema.describeSObjects(new List<String> { GenMigrationApplication.namespacePrefix + 'template_configuration__C' });

			if (getGenTemplateSobject.get(0).getSobjectType() != null) {

				Permissions.verifyIsQueryable(getGenTemplateSobject.get(0).getSobjectType(), new List<String> {
					'Id',
					'Name',
					GenMigrationApplication.namespacePrefix + 'Object_Mappings__c',
					GenMigrationApplication.namespacePrefix + 'Previewed_Documents__c',
					GenMigrationApplication.namespacePrefix + 'Sample__c',
					GenMigrationApplication.namespacePrefix + 'Signer_Mappings__c',
					GenMigrationApplication.namespacePrefix + 'Starting_Object__c',
					GenMigrationApplication.namespacePrefix + 'Steps_Completed__c',
					GenMigrationApplication.namespacePrefix + 'Use_All_Templates__c',
					GenMigrationApplication.namespacePrefix + 'Use_Current_Record__c'
				});
			}

			Id apexJobId = Database.executeBatch(new GenMigrationBatch('dsgen__Template_Configuration__c'));
			// Saving Batch Job Id
			GenMigrationSettings__c genSetting = GenMigrationSettings__c.getOrgDefaults();
			genSetting.TemplateMigrationBatchId__c = apexJobId;
			upsert genSetting;
			return apexJobId;
		} catch (Exception ex) {
			throw Controller.wrapException(ex, 'Failed to Create Templates in DAL');
		}
	}

	// Calling this method FROM Batch class finish method to update custom setting for user migration
	public static void updateUserGenCustomSettings() {
		GenMigrationSettings__c genSetting = GenMigrationApplication.getGenSettings();
		if (genSetting.UserMigrationBatchId__c != null) {
			genSetting.GenUsersMigrated__c = true;
			genSetting.UserMigrationBatchStatus__c = '';
		}
		update genSetting;
	}

	// Calling this method FROM Batch class finish method to update custom setting for template migration
	public static void updateTemplateGenCustomSettings() {
		GenMigrationSettings__c genSetting = GenMigrationApplication.getGenSettings();
		if (genSetting.templateMigrationBatchId__c != null) {
			genSetting.GenTemplatesMigrated__c = true;
			genSetting.TemplateMigrationBatchStatus__c = '';
		}
		update genSetting;
	}

	// On Template or User migration sucess,sending Email to logged in user
	public static void generateEmail(final String getEmailSubject, final String getEmailBody) {
		try {
			Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
			email.setToAddresses(new List<String> { UserInfo.getUserEmail() });
			email.setSubject(getEmailSubject);
			email.setHTMLBody(getEmailBody);
			Messaging.SingleEmailMessage[] messages = new List <Messaging.SingleEmailMessage> { email };
			Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
		} catch (Exception ex) {
		}
	}
}